# 数据库名
database: boundary_in
# postgresql模式名称
schema-name:
# 用户名
username: root
# 密码
password: root
# 主机地址
host: localhost
# 端口
port: 43306
# 连接字符串查询参数
query: parseTime=True&loc=Local&timeout=3000ms
# 是否打印日志
log-mode: false
# 编码方式
charset: utf8mb4
# 最大连接数
max-conns: 800
# 最大空闲数
max-idle-conns: 100
